##
##acme_hello_homepage:
#    path:     /hello/{name}
#    defaults: { _controller: AcmeHelloBundle:Default:index }
##
index:
    path:     /hello/index
    defaults: { _controller: AcmeHelloBundle:Default:index }

comfirm:
    path:     /hello/confirm
    defaults: { _controller: AcmeHelloBundle:Default:comfirm }
    
complete:
    path:     /hello/complete
    defaults: { _controller: AcmeHelloBundle:Default:complete }
